name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0.2'

      - name: Install dependencies
        run: composer install


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0.2'      
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.REMOTE_PORT }}
            passphrase: ${{ secrets.KEY_PASSPHRASE }}
            
            script: |
              cd ${{ secrets.REMOTE_PATH }}
              git pull ${{secrets.REPO_URL}}
      - name: Update remote database
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_DB_USER: ${{ secrets.REMOTE_DB_USER }}
          REMOTE_DB_PASSWORD: ${{ secrets.REMOTE_DB_PASSWORD }}
          REMOTE_DB_NAME: ${{ secrets.REMOTE_DB_NAME }}
        run: |
          mysql -h $REMOTE_HOST -u $REMOTE_DB_USER -p$REMOTE_DB_PASSWORD $REMOTE_DB_NAME < db/brickyard.sql