name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0.2'

      - name: Install dependencies
        run: composer install

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0.2'      

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.6  # Check for the latest version
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_port : ${{ secrets.REMOTE_PORT }}  # Default to port 22 if REMOTE_PORT is not set
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          script: |
            echo "Changing directory to ${{ secrets.REMOTE_PATH }}"
            cd ${{ secrets.REMOTE_PATH }}
            echo "Pulling from repository URL: ${{ secrets.REPO_URL }}"
            git pull ${{ secrets.REPO_URL }}
